# -*- coding: utf-8 -*-
"""ID/X Partners Data Scientist .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MlBfqXuVh95lvnOK4DUyAu20XtBpL11I

# ID/X Partners Data Scientist
"""

!gdown --id 1sL2joWOAlk4DkhDFNmrs7DnlqpO8mVeO

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix,  precision_score, recall_score, f1_score, roc_auc_score

df = pd.read_csv('/content/loan_data_2007_2014.csv')
df.drop('Unnamed: 0', axis=1, inplace=True)
df.tail()

df.info()

missing_columns_count = (df.isnull().sum() > 0).sum()
print(f"Jumlah kolom yang memiliki missing value: {missing_columns_count}")

# 1. Melihat daftar kolom numerik
numerical_cols = df.select_dtypes(include=['int64', 'float64']).columns
print("Kolom Numerik:", list(numerical_cols))
print("Jumlah kolom numerik:", len(numerical_cols))

# 2. Melihat daftar kolom kategorikal
categorical_cols = df.select_dtypes(include=['object']).columns
print("\nKolom Kategorikal:", list(categorical_cols))
print("Jumlah kolom kategorikal:", len(categorical_cols))

"""# Missing Value"""

df.isnull().sum()

df = df.dropna(axis=1, how='all')

threshold = len(df) * 0.6
df = df.dropna(thresh=threshold, axis=1)

df.isnull().sum()

for col in df.select_dtypes(include=['float64', 'int64']).columns:
    if df[col].isnull().sum() > 0:
        df[col].fillna(df[col].median(), inplace=True)

for col in df.select_dtypes(include=['object']).columns:
    if df[col].isnull().sum() > 0:
        df[col].fillna(df[col].mode()[0], inplace=True)

df.info()

df.isnull().sum()

"""# Duplicate Data"""

df.duplicated().sum()

"""# Statistical Analysis"""

df.describe().T

display(df.select_dtypes(include=['object']).describe().T)

"""# Univariate Analysis"""

plt.figure(figsize=(9, 4))
sns.histplot(df['loan_amnt'], kde=True, color='#d98b72')
plt.title('Univariate Analysis: Distribusi Jumlah Pinjaman (Loan Amount)')
plt.xlabel('Loan Amount')
plt.ylabel('Frekuensi')
plt.show()

plt.figure(figsize=(6, 3))
sns.countplot(x='term', data=df, palette='viridis')
plt.title('Univariate Analysis: Distribusi Term Pinjaman')
plt.xlabel('Term')
plt.ylabel('Jumlah')
plt.show()

"""# Bivariate Analysis"""

plt.figure(figsize=(8, 4))
sns.boxplot(x='term', y='loan_amnt', data=df, palette='Set2')
plt.title('Bivariate Analysis: Loan Amount Berdasarkan Term')
plt.xlabel('Term')
plt.ylabel('Loan Amount')
plt.show()

"""# Multivariate Analysis"""

plt.figure(figsize=(12, 9))
numeric_cols = df.select_dtypes(include=['float64', 'int64']).columns
correlation_matrix = df[numeric_cols].corr()

sns.heatmap(correlation_matrix, annot=False, cmap='coolwarm', linewidths=0.5)
plt.title('Correlation Heatmap Antar Variabel Numerik')
plt.show()

print(df['loan_status'].value_counts())

def map_loan_status(status):
    # Status yang dikategorikan sebagai Bad Loan / Risiko Tinggi (1)
    bad_status = [
        'Charged Off',
        'Default',
        'Late (31-120 days)',
        'Late (16-30 days)',
        'In Grace Period',
        'Does not meet the credit policy. Status:Charged Off'
    ]

    if status in bad_status:
        return 1
    else:
        return 0

# Terapkan ke dataframe untuk membuat kolom target baru
df['target'] = df['loan_status'].apply(map_loan_status)

# Cek hasil sebaran targetnya (0 vs 1)
print(df['target'].value_counts())

"""# Feature Engineering"""

useless_cols = ['id', 'member_id', 'url', 'title', 'emp_title', 'zip_code']

# B. Mengatasi Multikolinearitas (Membuang kolom fitur finansial yang kembar/redundan berdasarkan heatmap)
# Kita pertahankan 'loan_amnt', dan buang kembarannya yang korelasinya hampir 1 (merah pekat)
redundant_cols = ['funded_amnt', 'funded_amnt_inv']

# Menggabungkan daftar kolom yang akan dibuang
columns_to_drop = useless_cols + redundant_cols

# Menghapus kolom tersebut dari dataframe (pastikan hanya membuang yang ada di dataframe)
df_model = df.drop(columns=[col for col in columns_to_drop if col in df.columns], errors='ignore')

"""# Feature Encoding"""

le = LabelEncoder()

# Mengambil semua sisa kolom yang bertipe data teks (object)
object_cols = df_model.select_dtypes(include=['object']).columns

# Mengubah setiap kolom teks menjadi angka
for col in object_cols:
    df_model[col] = le.fit_transform(df_model[col].astype(str))

"""# Train test Split"""

X = df_model.drop(columns=['target'])
y = df_model['target']

X.sample(10)

y.sample(10)

X_encoded = pd.get_dummies(X, drop_first=False, dtype=int)

X_encoded

X_train, X_test, y_train, y_test = train_test_split(X_encoded, y, test_size=0.3, random_state=42)

y_train.value_counts(normalize=True) * 100

"""# Imbalance Data"""

from imblearn.over_sampling import SMOTE
from collections import Counter
print(f"Sebelum SMOTE: {Counter(y_train)}")

smote = SMOTE(random_state=42)
X_train, y_train = smote.fit_resample(X_train, y_train)

print(f"Setelah SMOTE: {Counter(y_train)}")

"""# StandardScaler"""

from sklearn.preprocessing import StandardScaler, OneHotEncoder
scaler = StandardScaler()
num_cols = ['loan_amnt', 'annual_inc', 'installment', 'dti']
X_train[num_cols] = scaler.fit_transform(X_train[num_cols])

X

X_train

y_train

"""# Modeling"""

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier

models = {
    "Logistic Regression": LogisticRegression(max_iter=1000, random_state=42),
    "Decision Tree": DecisionTreeClassifier(random_state=42),
    "Random Forest": RandomForestClassifier(random_state=42, n_jobs=-1),
    "XGBoost": XGBClassifier(random_state=42, n_jobs=-1, eval_metric='logloss')
}

summary_list = []
for name, model in models.items():
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)

    # Ambil probabilitas untuk ROC-AUC (jika tersedia)
    if hasattr(model, "predict_proba"):
        y_proba = model.predict_proba(X_test)[:, 1]
        roc_auc = roc_auc_score(y_test, y_proba)
    else:
        roc_auc = "N/A" # Beberapa model mungkin tidak punya predict_proba

    # Simpan hasil ke dictionary
    summary_list.append({
        'Algorithm': name,
        'Accuracy': accuracy_score(y_test, y_pred),
        'Precision': precision_score(y_test, y_pred),
        'Recall': recall_score(y_test, y_pred),
        'F1-Score': f1_score(y_test, y_pred),
        'ROC-AUC': roc_auc
    })

# Ubah menjadi DataFrame agar rapi
df_comparison = pd.DataFrame(summary_list)
display(df_comparison.sort_values(by='F1-Score', ascending=False).round(3))

import pandas as pd
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score

def calculate_gap(model, X_train, y_train, X_test, y_test, model_name):
    # Prediksi Train
    y_train_pred = model.predict(X_train)
    y_train_proba = model.predict_proba(X_train)[:, 1] if hasattr(model, "predict_proba") else None

    # Prediksi Test
    y_test_pred = model.predict(X_test)
    y_test_proba = model.predict_proba(X_test)[:, 1] if hasattr(model, "predict_proba") else None

    # Hitung Metrik & Gap (dalam persen)
    res = {
        'Model': model_name,
        'Accuracy Gap (%)': (accuracy_score(y_train, y_train_pred) - accuracy_score(y_test, y_test_pred)) * 100,
        'Precision Gap (%)': (precision_score(y_train, y_train_pred) - precision_score(y_test, y_test_pred)) * 100,
        'Recall Gap (%)': (recall_score(y_train, y_train_pred) - recall_score(y_test, y_test_pred)) * 100,
        'F1-Score Gap (%)': (f1_score(y_train, y_train_pred) - f1_score(y_test, y_test_pred)) * 100
    }

    # Tambahkan ROC-AUC Gap jika ada probabilitas
    if y_train_proba is not None and y_test_proba is not None:
        res['ROC-AUC Gap (%)'] = (roc_auc_score(y_train, y_train_proba) - roc_auc_score(y_test, y_test_proba)) * 100
    else:
        res['ROC-AUC Gap (%)'] = 0

    return res

gap_results = []

for name, model_obj in models.items():
    gap_data = calculate_gap(model_obj, X_train, y_train, X_test, y_test, name)
    gap_results.append(gap_data)

# Ubah menjadi DataFrame
df_gap = pd.DataFrame(gap_results)

# Membulatkan hasil angka agar rapi (3 angka di belakang koma)
df_gap = df_gap.round(3)

# Tampilkan Tabel
display(df_gap)

"""## hyperparameter

### Decision Tree
"""

from sklearn.model_selection import RandomizedSearchCV
model_dt = DecisionTreeClassifier(random_state=42)
param_space = {
    'criterion': ['gini', 'entropy'],
    'max_depth': [3, 5, 10, 15],
    'min_samples_split': [2, 5, 10, 20],
    'min_samples_leaf': [10, 20, 50]
  }

random_search_dt = RandomizedSearchCV(model_dt, param_space, n_iter=2, cv=3, n_jobs=-1, scoring= 'f1', random_state=42)
random_search_dt.fit(X_train, y_train)

import pandas as pd

# 1. Ambil dictionary parameter terbaik dari hasil random_search
best_params_dt= random_search_dt.best_params_

# 2. Ubah menjadi DataFrame agar rapi seperti tabel
df_best_hyperparameters = pd.DataFrame(list(best_params_dt.items()), columns=['Best Hyperparameter', 'Value'])

# 3. Tampilkan tabelnya
print("=== Tabel Best Hyperparameters Decision Tree ===")
display(df_best_hyperparameters)

"""### XGBoost"""

from sklearn.model_selection import RandomizedSearchCV
model_xgb = XGBClassifier(random_state=42)
param_space = {
    'n_estimators': [100, 200, 300],
    'learning_rate': [0.01, 0.05, 0.1],
    'max_depth': [5, 6, 7],
    'gamma': [0, 0.1, 0.2],
    'reg_lambda': [10, 50, 100]}

random_search_xgb = RandomizedSearchCV(model_xgb, param_space, n_iter=2, cv=3, n_jobs=-1, scoring= 'f1', random_state=42)
random_search_xgb.fit(X_train, y_train)

import pandas as pd

# 1. Ambil dictionary parameter terbaik dari hasil random_search
best_params_xgb = random_search_xgb.best_params_

# 2. Ubah menjadi DataFrame agar rapi seperti tabel
df_best_hyperparameters = pd.DataFrame(list(best_params_xgb.items()), columns=['Best Hyperparameter', 'Value'])

# 3. Tampilkan tabelnya
print("=== Tabel Best Hyperparameters XGBoost ===")
display(df_best_hyperparameters)

"""### Random Forest"""

model_rf = RandomForestClassifier(random_state=42)
param_space = {
    'n_estimators': [100],
    'max_depth': [5],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [10],
    'criterion': ['gini', 'entropy']
    }

random_search_rf = RandomizedSearchCV(model_rf, param_space, n_iter=2, cv=3, n_jobs=-1, scoring= 'f1', random_state=42)
random_search_rf.fit(X_train, y_train)

# 1. Ambil dictionary parameter terbaik dari hasil random_search
best_params_rf = random_search_rf.best_params_

# 2. Ubah menjadi DataFrame agar rapi seperti tabel
df_best_hyperparameters = pd.DataFrame(list(best_params_rf.items()), columns=['Best Hyperparameter', 'Value'])

# 3. Tampilkan tabelnya
print("=== Tabel Best Hyperparameters Random Forest ===")
display(df_best_hyperparameters)

"""### Hasil Setelah Hyperparameter Tuning"""

tuned_models_list = [
    ('Decision Tree', random_search_dt.best_estimator_),
    ('Random Forest', random_search_rf.best_estimator_),
    ('XGBoost', random_search_xgb.best_estimator_)
]

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score
import pandas as pd

final_results = []

for name, model in tuned_models_list:
    # Prediksi menggunakan data test
    y_pred = model.predict(X_test)

    # Ambil probabilitas untuk ROC-AUC
    if hasattr(model, "predict_proba"):
        y_proba = model.predict_proba(X_test)[:, 1]
        roc_auc = roc_auc_score(y_test, y_proba)
    else:
        roc_auc = "N/A"

    # Simpan hasil ke dictionary
    final_results.append({
        'Algorithm': name,
        'Accuracy': accuracy_score(y_test, y_pred),
        'Precision': precision_score(y_test, y_pred),
        'Recall': recall_score(y_test, y_pred),
        'F1-Score': f1_score(y_test, y_pred),
        'ROC-AUC': roc_auc
    })

# Tampilkan tabel final
df_final_comparison = pd.DataFrame(final_results)
print("=== PERBANDINGAN FINAL SETELAH HYPERPARAMETER TUNING ===")
display(df_final_comparison.sort_values(by='F1-Score', ascending=False).round(3))

# List model yang sudah di-tuning (sama seperti variabel kamu)
models_to_evaluate = [
    ('Decision Tree', random_search_dt.best_estimator_),
    ('Random Forest', random_search_rf.best_estimator_),
    ('XGBoost', random_search_xgb.best_estimator_)
]

final_report = []
dataset_order = ['Train', 'Test', 'Gap (%)']

for name, model in models_to_evaluate:
    # Prediksi
    y_train_pred = model.predict(X_train)
    y_test_pred = model.predict(X_test)
    y_train_proba = model.predict_proba(X_train)[:, 1]
    y_test_proba = model.predict_proba(X_test)[:, 1]

    # Hitung metrik
    data = {
        'Accuracy': [accuracy_score(y_train, y_train_pred), accuracy_score(y_test, y_test_pred)],
        'Precision': [precision_score(y_train, y_train_pred), precision_score(y_test, y_test_pred)],
        'Recall': [recall_score(y_train, y_train_pred), recall_score(y_test, y_test_pred)],
        'F1-Score': [f1_score(y_train, y_train_pred), f1_score(y_test, y_test_pred)],
        'ROC-AUC': [roc_auc_score(y_train, y_train_proba), roc_auc_score(y_test, y_test_proba)]
    }

    df_model = pd.DataFrame(data, index=['Train', 'Test'])
    df_model.loc['Gap (%)'] = (df_model.loc['Train'] - df_model.loc['Test']) * 100
    df_model.insert(0, 'Model', name)
    df_model = df_model.reset_index().rename(columns={'index': 'Dataset'})
    final_report.append(df_model)

# 2. Gabungkan hasil
df_final_report = pd.concat(final_report, ignore_index=True)

# 3. Urutkan berdasarkan F1-Score pada baris 'Test' (Paling tinggi di atas)
# Kita buat tabel bantu untuk sortir
df_sort = df_final_report[df_final_report['Dataset'] == 'Test'].sort_values(by='F1-Score', ascending=False)
ordered_models = df_sort['Model'].tolist()

# Terapkan urutan tersebut ke tabel utama
df_final_report['Dataset'] = pd.Categorical(
    df_final_report['Dataset'],
    categories=dataset_order,
    ordered=True
)

# 3. Urutkan berdasarkan Model dan Dataset (urutan custom tadi)
df_final_report = df_final_report.sort_values(['Model', 'Dataset'])

# Tampilkan dengan pembulatan 3 angka
display(df_final_report.round(3))

def create_styled_comparison(model, X_train, y_train, X_test, y_test):
    # 1. Prediksi (Gunakan model yang sudah di-fit dengan random_state=42)
    y_train_pred = model.predict(X_train)
    y_test_pred = model.predict(X_test)

    # Probabilitas untuk ROC-AUC
    y_train_proba = model.predict_proba(X_train)[:, 1]
    y_test_proba = model.predict_proba(X_test)[:, 1]

    # 2. Hitung Metrik Train
    metrics_train = {
        'Accuracy': accuracy_score(y_train, y_train_pred),
        'Precision': precision_score(y_train, y_train_pred),
        'Recall': recall_score(y_train, y_train_pred),
        'F1-Score': f1_score(y_train, y_train_pred),
        'ROC-AUC': roc_auc_score(y_train, y_train_proba)
    }

    # 3. Hitung Metrik Test
    metrics_test = {
        'Accuracy': accuracy_score(y_test, y_test_pred),
        'Precision': precision_score(y_test, y_test_pred),
        'Recall': recall_score(y_test, y_test_pred),
        'F1-Score': f1_score(y_test, y_test_pred),
        'ROC-AUC': roc_auc_score(y_test, y_test_proba)
    }

    # 4. Gabungkan ke DataFrame
    df = pd.DataFrame([metrics_train, metrics_test], index=['Train', 'Test'])

    # 5. Tambahkan Baris Gap (%)
    # Rumus: (Train - Test) * 100
    df.loc['Gap (%)'] = (df.loc['Train'] - df.loc['Test']) * 100

    return df.round(3)

# Contoh eksekusi untuk salah satu model hasil tuning kamu
# Pastikan saat inisialisasi model/search sebelumnya sudah pakai random_state=42
# Contoh: RandomForestClassifier(random_state=42)
print("=== TABEL EVALUASI MODEL ===")
display(create_styled_comparison(random_search_xgb.best_estimator_, X_train, y_train, X_test, y_test))

"""## Confusion Matrix"""

from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
from matplotlib.colors import LinearSegmentedColormap

colors = ["#ffffff", "#ebb7a2", "#d98b72"]
cmap_peach = LinearSegmentedColormap.from_list("custom_peach", colors)

# 1. Ambil nama dan model terbaik (urutan pertama setelah disortir tadi)
# Karena df_final_comparison disortir berdasarkan F1-Score,
# kita ambil index dari model XGBoost yang ada di posisi teratas.
best_model_tuple = tuned_models_list[2]
best_model_name = best_model_tuple[0]
best_model_obj = best_model_tuple[1]

# 2. Lakukan prediksi menggunakan X_test
y_pred_best = best_model_obj.predict(X_test)

# 3. Buat Confusion Matrix
cm = confusion_matrix(y_test, y_pred_best)

# 4. Visualisasi
plt.figure(figsize=(8, 6))
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=['Good Loan', 'Bad Loan'])
disp.plot(cmap=cmap_peach, values_format='d')

plt.title(f'Confusion Matrix - {best_model_name}')
plt.show()

from xgboost import plot_importance

# Menampilkan 10 fitur paling berpengaruh menurut XGBoost
plt.figure(figsize=(10, 6))
plot_importance(best_model_obj, max_num_features=10, height=0.6, color='#d98b72')
plt.grid(False)
plt.title("Top 10 Feature Importance - XGBoost Credit Risk")
plt.show()

"""# Data Set"""

import joblib

# Mengambil model XGBoost terbaik dari hasil tuning sebelumnya
best_model = random_search_xgb.best_estimator_

# 1. Simpan Daftar Fitur (Sangat penting agar urutan kolom saat deploy nanti tidak tertukar)
feature_names = X_train.columns.tolist()
joblib.dump(feature_names, 'feature_names.joblib')

# 2. Simpan Scaler
joblib.dump(scaler, 'scaler.joblib')

# 3. Simpan Model
joblib.dump(best_model, 'model_credit_risk_xgb.joblib')

# 4. Simpan Data X_train (Opsional, sangat berguna jika nanti butuh data sampel untuk testing aplikasi)
joblib.dump(X_train, 'X_train.joblib')

print("✅ Semua file berhasil disimpan dengan benar untuk proyek Credit Risk!")
print(f"Total ada {len(feature_names)} fitur yang disimpan.")

# Mengonversi X_train menjadi file CSV
X_train.to_csv('template_bulk_upload.csv', index=False)

print("File CSV berhasil disimpan sebagai template bulk upload!")